### ISSUE TITLE
Can I pass a parameter to decorateor? 

### ISSUE THREAD

**Issue by changweige** [termoshtt/deco#1]
In Python, we can also pass parameters to decorators.
Does this rust deco have such a capability too?
It will be quite useful!

**Comment by termoshtt** [comment]
>  Does this rust deco have such a capability too?

It cannot currently, but I think it is possible potentially.

**Comment by changweige** [comment]
Cool.
Better it can be used in impl{} either. :-)

**Comment by termoshtt** [comment]
FYI: I found a similar project https://github.com/Manishearth/rust-adorn

**Comment by changweige** [comment]
> FYI: I found a similar project https://github.com/Manishearth/rust-adorn

Thanks, I once found this project too. But it seems that it can't receive any parameters for decorator if I understand correctly.
